version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8-browsers
    environment:
      GITHUB_PAGES: 'https://angular-seattle.github.io/'
      UPDATE_SCREENSHOTS: '0'
    steps:
      - checkout

      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: google-chrome --version

      - run: yarn install
      - run: yarn run webdriver-update

      - run: xvfb-run -a $(npm bin)/protractor protractor.conf.js --specs='e2e/tractor.e2e-spec.ts' --directConnect=true
